apiVersion: skaffold/v4beta9
kind: Config
deploy:
  kubectl: {}
manifests:
  rawYaml:
    - ./infra/k8s/*
    - ./infra/k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: germanyn/auth
      context: services/auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
    - image: germanyn/tickets
      context: services/tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
    - image: germanyn/orders
      context: services/orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
    - image: germanyn/expiration
      context: services/expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: germanyn/payments
      context: services/payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: germanyn/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: src/**/*.tsx
            dest: .
          - src: src/**/*.ts
            dest: .
          - src: src/**/*.js
            dest: .
          - src: src/**/*.jsx
            dest: .