@authUrl = https://ticketing.dev/api/users
@baseUrl = https://ticketing.dev/api/orders

###
# Valid signup
# @name signup
POST {{authUrl}}/signup
content-type: application/json

{
    "email": "test@email.com",
    "password": "password"
}

###
# Create ticket
# @name createOrder
POST {{baseUrl}}
content-type: application/json

{
    "ticketId": "65f73cf7420ff5cc90d9df90"
}
