name: tests-payments

on:
  pull_request:
    paths:
      - 'services/payments/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i -w payments && npm run -w payments test:ci
